name: patternlock
description: A new Flutter project.

# Prevent publishing to pub.dev
publish_to: 'none'

# App versioning
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^9.2.4
  image_picker: ^1.1.0
  path_provider: ^2.1.2
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/AppLogo.png  # make sure this matches your actual path

flutter_icons:
  android: true
  ios: true
  image_path: "assets/AppLogo.png"
